<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.11" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="8.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\HelpDesk.Backend.Application\HelpDesk.Backend.Application.csproj" />
    <ProjectReference Include="..\..\Core\HelpDesk.Backend.Domain\HelpDesk.Backend.Domain.csproj" />
    <ProjectReference Include="..\..\Infrastructure\HelpDesk.Backend.Infrastructure\HelpDesk.Backend.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\ApiMessages.Designer.cs">
      <DependentUpon>ApiMessages.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
    <EmbeddedResource Update="Resources\ApiMessages.resx">
      <SubType>Designer</SubType>
      <LastGenOutput>ApiMessages.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

</Project>
