// <auto-generated />
#nullable enable
namespace HelpDesk.Backend.Api.Resources;

using System.Globalization;
using System.Resources;

[global::System.CodeDom.Compiler.GeneratedCode(
    "System.Resources.Tools.StronglyTypedResourceBuilder",
    "8.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCode]
[global::System.Runtime.CompilerServices.CompilerGenerated]
public class ApiMessages
{
    private static ResourceManager? resourceManager;
    private static CultureInfo? resourceCulture;

    internal ApiMessages()
    {
    }

    public static ResourceManager ResourceManager =>
        resourceManager ??= new ResourceManager(
            "HelpDesk.Backend.Api.Resources.ApiMessages",
            typeof(ApiMessages).Assembly);

    public static CultureInfo? Culture
    {
        get => resourceCulture;
        set => resourceCulture = value;
    }

    public static string InvalidCredentialsTitle => GetString(nameof(InvalidCredentialsTitle));
    public static string AccessDeniedTitle => GetString(nameof(AccessDeniedTitle));
    public static string ResourceNotFoundTitle => GetString(nameof(ResourceNotFoundTitle));
    public static string DomainConflictTitle => GetString(nameof(DomainConflictTitle));
    public static string ConcurrencyConflictTitle => GetString(nameof(ConcurrencyConflictTitle));
    public static string ConcurrencyConflict => GetString(nameof(ConcurrencyConflict));
    public static string UniquenessConflictTitle => GetString(nameof(UniquenessConflictTitle));
    public static string UniquenessConflict => GetString(nameof(UniquenessConflict));
    public static string ConflictTitle => GetString(nameof(ConflictTitle));
    public static string InvalidRequestTitle => GetString(nameof(InvalidRequestTitle));
    public static string InvalidRequest => GetString(nameof(InvalidRequest));
    public static string UnexpectedErrorTitle => GetString(nameof(UnexpectedErrorTitle));
    public static string UnexpectedError => GetString(nameof(UnexpectedError));
    public static string ValidationTitle => GetString(nameof(ValidationTitle));
    public static string Validation => GetString(nameof(Validation));
    public static string ActorClaimRequired => GetString(nameof(ActorClaimRequired));
    public static string InvalidFieldValue => GetString(nameof(InvalidFieldValue));
    public static string InvalidFields => GetString(nameof(InvalidFields));
    public static string UnauthenticatedTitle => GetString(nameof(UnauthenticatedTitle));
    public static string ValidAccessTokenRequired => GetString(nameof(ValidAccessTokenRequired));
    public static string OperationNotAllowed => GetString(nameof(OperationNotAllowed));
    public static string TooManyAttemptsTitle => GetString(nameof(TooManyAttemptsTitle));
    public static string TooManyLoginAttempts => GetString(nameof(TooManyLoginAttempts));
    public static string SwaggerBearerDescription => GetString(nameof(SwaggerBearerDescription));

    private static string GetString(string name) =>
        ResourceManager.GetString(name, resourceCulture) ??
        throw new MissingManifestResourceException(
            $"No se encontró el recurso '{name}'.");
}
