// <auto-generated />
using System;
using HelpDesk.Backend.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelpDesk.Backend.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HelpDeskDbContext))]
    partial class HelpDeskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HelpDesk.Backend.Domain.Categories.SlaPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("priority");

                    b.Property<long>("ResponseTime")
                        .HasColumnType("bigint")
                        .HasColumnName("response_time_ticks");

                    b.Property<Guid>("support_category_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("support_category_id");

                    b.HasKey("Id");

                    b.HasIndex("support_category_id", "Priority")
                        .IsUnique()
                        .HasDatabaseName("ux_sla_policies_category_priority");

                    b.ToTable("sla_policies", null, t =>
                        {
                            t.HasCheckConstraint("ck_sla_policies_response_time", "[response_time_ticks] > 0");
                        });
                });

            modelBuilder.Entity("HelpDesk.Backend.Domain.Categories.SupportCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at_utc");

                    b.Property<byte[]>("row_version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_support_categories_name");

                    b.ToTable("support_categories", (string)null);
                });

            modelBuilder.Entity("HelpDesk.Backend.Domain.Tickets.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("closed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<Guid>("CreatorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("creator_user_id");

                    b.Property<Guid?>("CurrentTechnicianUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("current_technician_user_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("ticket_number");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset?>("ResolvedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("resolved_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("subject");

                    b.Property<Guid>("SupportCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("support_category_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at_utc");

                    b.Property<byte[]>("row_version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId")
                        .HasDatabaseName("ix_tickets_creator_user_id");

                    b.HasIndex("CurrentTechnicianUserId")
                        .HasDatabaseName("ix_tickets_current_technician_user_id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("ux_tickets_ticket_number");

                    b.HasIndex("SupportCategoryId")
                        .HasDatabaseName("ix_tickets_support_category_id");

                    b.HasIndex("Status", "CreatedAtUtc")
                        .HasDatabaseName("ix_tickets_status_created_at_utc");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("HelpDesk.Backend.Domain.Tickets.TicketAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("assigned_at_utc");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assigned_by_user_id");

                    b.Property<DateTimeOffset?>("EndedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("ended_at_utc");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TechnicianUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("technician_user_id");

                    b.Property<Guid>("ticket_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("TechnicianUserId")
                        .HasDatabaseName("ix_ticket_assignments_technician_user_id");

                    b.HasIndex("ticket_id", "AssignedAtUtc")
                        .HasDatabaseName("ix_ticket_assignments_ticket_assigned_at_utc");

                    b.ToTable("ticket_assignments", (string)null);
                });

            modelBuilder.Entity("HelpDesk.Backend.Domain.Tickets.TicketComment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<bool>("SatisfiesResolutionRequirement")
                        .HasColumnType("bit")
                        .HasColumnName("satisfies_resolution_requirement");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .HasColumnName("type");

                    b.Property<Guid>("ticket_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("ticket_id", "CreatedAtUtc")
                        .HasDatabaseName("ix_ticket_comments_ticket_created_at_utc");

                    b.ToTable("ticket_comments", (string)null);
                });

            modelBuilder.Entity("HelpDesk.Backend.Domain.Tickets.TicketSlaCycle", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("BreachedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("breached_at_utc");

                    b.Property<DateTimeOffset>("DeadlineAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("deadline_at_utc");

                    b.Property<long>("Duration")
                        .HasColumnType("bigint")
                        .HasColumnName("duration_ticks");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("outcome");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset?>("RespondedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("responded_at_utc");

                    b.Property<Guid?>("ResponsibleTechnicianUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("responsible_technician_user_id");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("started_at_utc");

                    b.Property<Guid>("SupportCategoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("support_category_id");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("trigger");

                    b.Property<Guid>("ticket_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("ResponsibleTechnicianUserId")
                        .HasDatabaseName("ix_ticket_sla_cycles_responsible_technician_user_id");

                    b.HasIndex("SupportCategoryId");

                    b.HasIndex("Outcome", "DeadlineAtUtc")
                        .HasDatabaseName("ix_ticket_sla_cycles_outcome_deadline_at_utc");

                    b.HasIndex("ticket_id", "StartedAtUtc")
                        .HasDatabaseName("ix_ticket_sla_cycles_ticket_started_at_utc");

                    b.ToTable("ticket_sla_cycles", null, t =>
                        {
                            t.HasCheckConstraint("ck_ticket_sla_cycles_duration", "[duration_ticks] > 0");
                        });
                });

            modelBuilder.Entity("HelpDesk.Backend.Domain.Tickets.TicketStatusChange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ChangedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("changed_at_utc");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("changed_by_user_id");

                    b.Property<bool>("IsAutomatic")
                        .HasColumnType("bit")
                        .HasColumnName("is_automatic");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("new_status");

                    b.Property<string>("PreviousStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("previous_status");

                    b.Property<string>("Reason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("reason");

                    b.Property<Guid>("ticket_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("ticket_id", "ChangedAtUtc")
                        .HasDatabaseName("ix_ticket_status_history_ticket_changed_at_utc");

                    b.ToTable("ticket_status_history", (string)null);
                });

            modelBuilder.Entity("HelpDesk.Backend.Domain.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at_utc");

                    b.Property<byte[]>("row_version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("row_version");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ux_users_email");

                    b.HasIndex("Role", "IsActive")
                        .HasDatabaseName("ix_users_role_is_active");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_role_profile", "([role] = 'Technician' AND [technician_max_active_tickets] IS NOT NULL AND [supervisor_support_category_id] IS NULL) OR ([role] = 'Supervisor' AND [technician_max_active_tickets] IS NULL AND [supervisor_support_category_id] IS NOT NULL) OR ([role] IN ('User', 'SuperAdmin') AND [technician_max_active_tickets] IS NULL AND [supervisor_support_category_id] IS NULL)");

                            t.HasCheckConstraint("ck_users_technician_capacity", "[technician_max_active_tickets] IS NULL OR [technician_max_active_tickets] > 0");
                        });
                });

            modelBuilder.Entity("HelpDesk.Backend.Infrastructure.Persistence.Entities.TicketNumberSequenceState", b =>
                {
                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("year");

                    b.Property<int>("LastValue")
                        .HasColumnType("int")
                        .HasColumnName("last_value");

                    b.HasKey("Year");

                    b.ToTable("ticket_number_sequences", null, t =>
                        {
                            t.HasCheckConstraint("ck_ticket_number_sequences_last_value", "[last_value] BETWEEN 0 AND 999999");

                            t.HasCheckConstraint("ck_ticket_number_sequences_year", "[year] BETWEEN 2000 AND 9999");
                        });
                });

            modelBuilder.Entity("HelpDesk.Backend.Domain.Categories.SlaPolicy", b =>
                {
                    b.HasOne("HelpDesk.Backend.Domain.Categories.SupportCategory", null)
                        .WithMany("SlaPolicies")
                        .HasForeignKey("support_category_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HelpDesk.Backend.Domain.Tickets.Ticket", b =>
                {
                    b.HasOne("HelpDesk.Backend.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HelpDesk.Backend.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("CurrentTechnicianUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HelpDesk.Backend.Domain.Categories.SupportCategory", null)
                        .WithMany()
                        .HasForeignKey("SupportCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("HelpDesk.Backend.Domain.Tickets.TicketAssignment", b =>
                {
                    b.HasOne("HelpDesk.Backend.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HelpDesk.Backend.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("TechnicianUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HelpDesk.Backend.Domain.Tickets.Ticket", null)
                        .WithMany("Assignments")
                        .HasForeignKey("ticket_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HelpDesk.Backend.Domain.Tickets.TicketComment", b =>
                {
                    b.HasOne("HelpDesk.Backend.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HelpDesk.Backend.Domain.Tickets.Ticket", null)
                        .WithMany("Comments")
                        .HasForeignKey("ticket_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HelpDesk.Backend.Domain.Tickets.TicketSlaCycle", b =>
                {
                    b.HasOne("HelpDesk.Backend.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ResponsibleTechnicianUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HelpDesk.Backend.Domain.Categories.SupportCategory", null)
                        .WithMany()
                        .HasForeignKey("SupportCategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("HelpDesk.Backend.Domain.Tickets.Ticket", null)
                        .WithMany("SlaCycles")
                        .HasForeignKey("ticket_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HelpDesk.Backend.Domain.Tickets.TicketStatusChange", b =>
                {
                    b.HasOne("HelpDesk.Backend.Domain.Users.User", null)
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("HelpDesk.Backend.Domain.Tickets.Ticket", null)
                        .WithMany("StatusHistory")
                        .HasForeignKey("ticket_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HelpDesk.Backend.Domain.Users.User", b =>
                {
                    b.OwnsOne("HelpDesk.Backend.Domain.Users.SupervisorProfile", "SupervisorProfile", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("SupportCategoryId")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("supervisor_support_category_id");

                            b1.HasKey("UserId");

                            b1.HasIndex("SupportCategoryId")
                                .HasDatabaseName("ix_users_supervisor_support_category_id");

                            b1.ToTable("users");

                            b1.HasOne("HelpDesk.Backend.Domain.Categories.SupportCategory", null)
                                .WithMany()
                                .HasForeignKey("SupportCategoryId")
                                .OnDelete(DeleteBehavior.NoAction)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("HelpDesk.Backend.Domain.Users.TechnicianProfile", "TechnicianProfile", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("MaxActiveTickets")
                                .HasColumnType("int")
                                .HasColumnName("technician_max_active_tickets");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");

                            b1.OwnsMany("HelpDesk.Backend.Domain.Users.TechnicianCategory", "CategoryAssignments", b2 =>
                                {
                                    b2.Property<Guid>("technician_user_id")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<Guid>("SupportCategoryId")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("support_category_id");

                                    b2.HasKey("technician_user_id", "SupportCategoryId");

                                    b2.HasIndex("SupportCategoryId")
                                        .HasDatabaseName("ix_technician_categories_support_category_id");

                                    b2.ToTable("technician_categories", (string)null);

                                    b2.HasOne("HelpDesk.Backend.Domain.Categories.SupportCategory", null)
                                        .WithMany()
                                        .HasForeignKey("SupportCategoryId")
                                        .OnDelete(DeleteBehavior.NoAction)
                                        .IsRequired();

                                    b2.WithOwner()
                                        .HasForeignKey("technician_user_id");
                                });

                            b1.Navigation("CategoryAssignments");
                        });

                    b.Navigation("SupervisorProfile");

                    b.Navigation("TechnicianProfile");
                });

            modelBuilder.Entity("HelpDesk.Backend.Domain.Categories.SupportCategory", b =>
                {
                    b.Navigation("SlaPolicies");
                });

            modelBuilder.Entity("HelpDesk.Backend.Domain.Tickets.Ticket", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Comments");

                    b.Navigation("SlaCycles");

                    b.Navigation("StatusHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
